//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiXiAPIsamples.TransactionService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetTeamPaymentTransactionRequest", Namespace="http://schemas.datacontract.org/2004/07/FiXi.DataContract")]
    [System.SerializableAttribute()]
    public partial class GetTeamPaymentTransactionRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ApplicationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TeamIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ApplicationId {
            get {
                return this.ApplicationIdField;
            }
            set {
                if ((this.ApplicationIdField.Equals(value) != true)) {
                    this.ApplicationIdField = value;
                    this.RaisePropertyChanged("ApplicationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TeamId {
            get {
                return this.TeamIdField;
            }
            set {
                if ((this.TeamIdField.Equals(value) != true)) {
                    this.TeamIdField = value;
                    this.RaisePropertyChanged("TeamId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseBase", Namespace="http://schemas.datacontract.org/2004/07/FiXi.DataContract")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FiXiAPIsamples.TransactionService.SaveTeamPaymentResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FiXiAPIsamples.TransactionService.GetTeamPaymentTransactionResponse))]
    public partial class ResponseBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaveTeamPaymentResponse", Namespace="http://schemas.datacontract.org/2004/07/FiXi.DataContract")]
    [System.SerializableAttribute()]
    public partial class SaveTeamPaymentResponse : FiXiAPIsamples.TransactionService.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TeamPaymentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TransactionIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TeamPaymentID {
            get {
                return this.TeamPaymentIDField;
            }
            set {
                if ((this.TeamPaymentIDField.Equals(value) != true)) {
                    this.TeamPaymentIDField = value;
                    this.RaisePropertyChanged("TeamPaymentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TransactionID {
            get {
                return this.TransactionIDField;
            }
            set {
                if ((this.TransactionIDField.Equals(value) != true)) {
                    this.TransactionIDField = value;
                    this.RaisePropertyChanged("TransactionID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetTeamPaymentTransactionResponse", Namespace="http://schemas.datacontract.org/2004/07/FiXi.DataContract")]
    [System.SerializableAttribute()]
    public partial class GetTeamPaymentTransactionResponse : FiXiAPIsamples.TransactionService.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FiXiAPIsamples.TransactionService.TeamPaymentTransactionListView[] TeamPaymentTransactionViewListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FiXiAPIsamples.TransactionService.TeamPaymentTransactionListView[] TeamPaymentTransactionViewList {
            get {
                return this.TeamPaymentTransactionViewListField;
            }
            set {
                if ((object.ReferenceEquals(this.TeamPaymentTransactionViewListField, value) != true)) {
                    this.TeamPaymentTransactionViewListField = value;
                    this.RaisePropertyChanged("TeamPaymentTransactionViewList");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TeamPaymentTransactionListView", Namespace="http://schemas.datacontract.org/2004/07/FiXi.DataContract")]
    [System.SerializableAttribute()]
    public partial class TeamPaymentTransactionListView : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AdjustmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CreditField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal DebitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FiXiAPIsamples.TransactionService.DivisionBasicView DivisionBasicViewField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RoundField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FiXiAPIsamples.TransactionService.SeasonBasicView SeasonBasicViewField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FiXiAPIsamples.TransactionService.SportBasicView SportBasicViewField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TeamPaymentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TransactionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FiXiAPIsamples.TransactionService.TransactionTypeEnum TransactionTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Adjustment {
            get {
                return this.AdjustmentField;
            }
            set {
                if ((this.AdjustmentField.Equals(value) != true)) {
                    this.AdjustmentField = value;
                    this.RaisePropertyChanged("Adjustment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Created {
            get {
                return this.CreatedField;
            }
            set {
                if ((this.CreatedField.Equals(value) != true)) {
                    this.CreatedField = value;
                    this.RaisePropertyChanged("Created");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Credit {
            get {
                return this.CreditField;
            }
            set {
                if ((this.CreditField.Equals(value) != true)) {
                    this.CreditField = value;
                    this.RaisePropertyChanged("Credit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Debit {
            get {
                return this.DebitField;
            }
            set {
                if ((this.DebitField.Equals(value) != true)) {
                    this.DebitField = value;
                    this.RaisePropertyChanged("Debit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FiXiAPIsamples.TransactionService.DivisionBasicView DivisionBasicView {
            get {
                return this.DivisionBasicViewField;
            }
            set {
                if ((object.ReferenceEquals(this.DivisionBasicViewField, value) != true)) {
                    this.DivisionBasicViewField = value;
                    this.RaisePropertyChanged("DivisionBasicView");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Round {
            get {
                return this.RoundField;
            }
            set {
                if ((this.RoundField.Equals(value) != true)) {
                    this.RoundField = value;
                    this.RaisePropertyChanged("Round");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FiXiAPIsamples.TransactionService.SeasonBasicView SeasonBasicView {
            get {
                return this.SeasonBasicViewField;
            }
            set {
                if ((object.ReferenceEquals(this.SeasonBasicViewField, value) != true)) {
                    this.SeasonBasicViewField = value;
                    this.RaisePropertyChanged("SeasonBasicView");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FiXiAPIsamples.TransactionService.SportBasicView SportBasicView {
            get {
                return this.SportBasicViewField;
            }
            set {
                if ((object.ReferenceEquals(this.SportBasicViewField, value) != true)) {
                    this.SportBasicViewField = value;
                    this.RaisePropertyChanged("SportBasicView");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TeamPaymentId {
            get {
                return this.TeamPaymentIdField;
            }
            set {
                if ((this.TeamPaymentIdField.Equals(value) != true)) {
                    this.TeamPaymentIdField = value;
                    this.RaisePropertyChanged("TeamPaymentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TransactionId {
            get {
                return this.TransactionIdField;
            }
            set {
                if ((this.TransactionIdField.Equals(value) != true)) {
                    this.TransactionIdField = value;
                    this.RaisePropertyChanged("TransactionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FiXiAPIsamples.TransactionService.TransactionTypeEnum TransactionType {
            get {
                return this.TransactionTypeField;
            }
            set {
                if ((this.TransactionTypeField.Equals(value) != true)) {
                    this.TransactionTypeField = value;
                    this.RaisePropertyChanged("TransactionType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DivisionBasicView", Namespace="http://schemas.datacontract.org/2004/07/FiXi.DataContract")]
    [System.SerializableAttribute()]
    public partial class DivisionBasicView : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SeasonBasicView", Namespace="http://schemas.datacontract.org/2004/07/FiXi.DataContract")]
    [System.SerializableAttribute()]
    public partial class SeasonBasicView : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SportBasicView", Namespace="http://schemas.datacontract.org/2004/07/FiXi.DataContract")]
    [System.SerializableAttribute()]
    public partial class SportBasicView : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColorHTMLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextColorHTMLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ColorHTML {
            get {
                return this.ColorHTMLField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorHTMLField, value) != true)) {
                    this.ColorHTMLField = value;
                    this.RaisePropertyChanged("ColorHTML");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TextColorHTML {
            get {
                return this.TextColorHTMLField;
            }
            set {
                if ((object.ReferenceEquals(this.TextColorHTMLField, value) != true)) {
                    this.TextColorHTMLField = value;
                    this.RaisePropertyChanged("TextColorHTML");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransactionTypeEnum", Namespace="http://schemas.datacontract.org/2004/07/FiXi.DataContract")]
    public enum TransactionTypeEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TeamPayment = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaveTeamPaymentRequest", Namespace="http://schemas.datacontract.org/2004/07/FiXi.DataContract")]
    [System.SerializableAttribute()]
    public partial class SaveTeamPaymentRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AllocationSeriesIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ApplicationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DivisionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PosTransactionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RoundField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SeasonIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SportIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TeamIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AllocationSeriesID {
            get {
                return this.AllocationSeriesIDField;
            }
            set {
                if ((this.AllocationSeriesIDField.Equals(value) != true)) {
                    this.AllocationSeriesIDField = value;
                    this.RaisePropertyChanged("AllocationSeriesID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ApplicationId {
            get {
                return this.ApplicationIdField;
            }
            set {
                if ((this.ApplicationIdField.Equals(value) != true)) {
                    this.ApplicationIdField = value;
                    this.RaisePropertyChanged("ApplicationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Created {
            get {
                return this.CreatedField;
            }
            set {
                if ((this.CreatedField.Equals(value) != true)) {
                    this.CreatedField = value;
                    this.RaisePropertyChanged("Created");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DivisionID {
            get {
                return this.DivisionIDField;
            }
            set {
                if ((this.DivisionIDField.Equals(value) != true)) {
                    this.DivisionIDField = value;
                    this.RaisePropertyChanged("DivisionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PosTransactionID {
            get {
                return this.PosTransactionIDField;
            }
            set {
                if ((object.ReferenceEquals(this.PosTransactionIDField, value) != true)) {
                    this.PosTransactionIDField = value;
                    this.RaisePropertyChanged("PosTransactionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Round {
            get {
                return this.RoundField;
            }
            set {
                if ((this.RoundField.Equals(value) != true)) {
                    this.RoundField = value;
                    this.RaisePropertyChanged("Round");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SeasonID {
            get {
                return this.SeasonIDField;
            }
            set {
                if ((this.SeasonIDField.Equals(value) != true)) {
                    this.SeasonIDField = value;
                    this.RaisePropertyChanged("SeasonID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SportID {
            get {
                return this.SportIDField;
            }
            set {
                if ((this.SportIDField.Equals(value) != true)) {
                    this.SportIDField = value;
                    this.RaisePropertyChanged("SportID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TeamID {
            get {
                return this.TeamIDField;
            }
            set {
                if ((this.TeamIDField.Equals(value) != true)) {
                    this.TeamIDField = value;
                    this.RaisePropertyChanged("TeamID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://FiXi.Contracts/PrivateServices", ConfigurationName="TransactionService.ITransactionService")]
    public interface ITransactionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://FiXi.Contracts/PrivateServices/ITransactionService/GetTeamPaymentTransacti" +
            "ons", ReplyAction="http://FiXi.Contracts/PrivateServices/ITransactionService/GetTeamPaymentTransacti" +
            "onsResponse")]
        FiXiAPIsamples.TransactionService.GetTeamPaymentTransactionResponse GetTeamPaymentTransactions(FiXiAPIsamples.TransactionService.GetTeamPaymentTransactionRequest GetTeamPaymentTransactionRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://FiXi.Contracts/PrivateServices/ITransactionService/SaveTeamPayment", ReplyAction="http://FiXi.Contracts/PrivateServices/ITransactionService/SaveTeamPaymentResponse" +
            "")]
        FiXiAPIsamples.TransactionService.SaveTeamPaymentResponse SaveTeamPayment(FiXiAPIsamples.TransactionService.SaveTeamPaymentRequest SaveTeamPaymentRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITransactionServiceChannel : FiXiAPIsamples.TransactionService.ITransactionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TransactionServiceClient : System.ServiceModel.ClientBase<FiXiAPIsamples.TransactionService.ITransactionService>, FiXiAPIsamples.TransactionService.ITransactionService {
        
        public TransactionServiceClient() {
        }
        
        public TransactionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TransactionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransactionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransactionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FiXiAPIsamples.TransactionService.GetTeamPaymentTransactionResponse GetTeamPaymentTransactions(FiXiAPIsamples.TransactionService.GetTeamPaymentTransactionRequest GetTeamPaymentTransactionRequest) {
            return base.Channel.GetTeamPaymentTransactions(GetTeamPaymentTransactionRequest);
        }
        
        public FiXiAPIsamples.TransactionService.SaveTeamPaymentResponse SaveTeamPayment(FiXiAPIsamples.TransactionService.SaveTeamPaymentRequest SaveTeamPaymentRequest) {
            return base.Channel.SaveTeamPayment(SaveTeamPaymentRequest);
        }
    }
}
