//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiXiAPIsamples.MatchService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetMatchesByDateRangeRequest", Namespace="http://schemas.datacontract.org/2004/07/FiXi.DataContract")]
    [System.SerializableAttribute()]
    public partial class GetMatchesByDateRangeRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ApplicationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ApplicationId {
            get {
                return this.ApplicationIdField;
            }
            set {
                if ((this.ApplicationIdField.Equals(value) != true)) {
                    this.ApplicationIdField = value;
                    this.RaisePropertyChanged("ApplicationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseBase", Namespace="http://schemas.datacontract.org/2004/07/FiXi.DataContract")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FiXiAPIsamples.MatchService.GetMatchByIdResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FiXiAPIsamples.MatchService.GetMatchesByIdListResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FiXiAPIsamples.MatchService.GetMatchesByDateRangeResponse))]
    public partial class ResponseBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetMatchByIdResponse", Namespace="http://schemas.datacontract.org/2004/07/FiXi.DataContract")]
    [System.SerializableAttribute()]
    public partial class GetMatchByIdResponse : FiXiAPIsamples.MatchService.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FiXiAPIsamples.MatchService.MatchDetailView MatchDetailViewField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FiXiAPIsamples.MatchService.MatchDetailView MatchDetailView {
            get {
                return this.MatchDetailViewField;
            }
            set {
                if ((object.ReferenceEquals(this.MatchDetailViewField, value) != true)) {
                    this.MatchDetailViewField = value;
                    this.RaisePropertyChanged("MatchDetailView");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetMatchesByIdListResponse", Namespace="http://schemas.datacontract.org/2004/07/FiXi.DataContract")]
    [System.SerializableAttribute()]
    public partial class GetMatchesByIdListResponse : FiXiAPIsamples.MatchService.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FiXiAPIsamples.MatchService.MatchDetailView[] MatchDetailViewListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FiXiAPIsamples.MatchService.MatchDetailView[] MatchDetailViewList {
            get {
                return this.MatchDetailViewListField;
            }
            set {
                if ((object.ReferenceEquals(this.MatchDetailViewListField, value) != true)) {
                    this.MatchDetailViewListField = value;
                    this.RaisePropertyChanged("MatchDetailViewList");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetMatchesByDateRangeResponse", Namespace="http://schemas.datacontract.org/2004/07/FiXi.DataContract")]
    [System.SerializableAttribute()]
    public partial class GetMatchesByDateRangeResponse : FiXiAPIsamples.MatchService.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FiXiAPIsamples.MatchService.MatchListView[] MatchListViewListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FiXiAPIsamples.MatchService.MatchListView[] MatchListViewList {
            get {
                return this.MatchListViewListField;
            }
            set {
                if ((object.ReferenceEquals(this.MatchListViewListField, value) != true)) {
                    this.MatchListViewListField = value;
                    this.RaisePropertyChanged("MatchListViewList");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MatchListView", Namespace="http://schemas.datacontract.org/2004/07/FiXi.DataContract")]
    [System.SerializableAttribute()]
    public partial class MatchListView : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AllocationSeriesIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FiXiAPIsamples.MatchService.TeamBasicFinancialView AwayTeamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FiXiAPIsamples.MatchService.DivisionBasicView DivisionBasicViewField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FiXiAPIsamples.MatchService.TeamBasicFinancialView HomeTeamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ModifiedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FiXiAPIsamples.MatchService.ResourceListView[] ResourceListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RoundField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FiXiAPIsamples.MatchService.SeasonBasicView SeasonBasicViewField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FiXiAPIsamples.MatchService.SportBasicView SportBasicViewField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AllocationSeriesId {
            get {
                return this.AllocationSeriesIdField;
            }
            set {
                if ((this.AllocationSeriesIdField.Equals(value) != true)) {
                    this.AllocationSeriesIdField = value;
                    this.RaisePropertyChanged("AllocationSeriesId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FiXiAPIsamples.MatchService.TeamBasicFinancialView AwayTeam {
            get {
                return this.AwayTeamField;
            }
            set {
                if ((object.ReferenceEquals(this.AwayTeamField, value) != true)) {
                    this.AwayTeamField = value;
                    this.RaisePropertyChanged("AwayTeam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Created {
            get {
                return this.CreatedField;
            }
            set {
                if ((this.CreatedField.Equals(value) != true)) {
                    this.CreatedField = value;
                    this.RaisePropertyChanged("Created");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FiXiAPIsamples.MatchService.DivisionBasicView DivisionBasicView {
            get {
                return this.DivisionBasicViewField;
            }
            set {
                if ((object.ReferenceEquals(this.DivisionBasicViewField, value) != true)) {
                    this.DivisionBasicViewField = value;
                    this.RaisePropertyChanged("DivisionBasicView");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((this.EndTimeField.Equals(value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FiXiAPIsamples.MatchService.TeamBasicFinancialView HomeTeam {
            get {
                return this.HomeTeamField;
            }
            set {
                if ((object.ReferenceEquals(this.HomeTeamField, value) != true)) {
                    this.HomeTeamField = value;
                    this.RaisePropertyChanged("HomeTeam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Modified {
            get {
                return this.ModifiedField;
            }
            set {
                if ((this.ModifiedField.Equals(value) != true)) {
                    this.ModifiedField = value;
                    this.RaisePropertyChanged("Modified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FiXiAPIsamples.MatchService.ResourceListView[] ResourceList {
            get {
                return this.ResourceListField;
            }
            set {
                if ((object.ReferenceEquals(this.ResourceListField, value) != true)) {
                    this.ResourceListField = value;
                    this.RaisePropertyChanged("ResourceList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Round {
            get {
                return this.RoundField;
            }
            set {
                if ((this.RoundField.Equals(value) != true)) {
                    this.RoundField = value;
                    this.RaisePropertyChanged("Round");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FiXiAPIsamples.MatchService.SeasonBasicView SeasonBasicView {
            get {
                return this.SeasonBasicViewField;
            }
            set {
                if ((object.ReferenceEquals(this.SeasonBasicViewField, value) != true)) {
                    this.SeasonBasicViewField = value;
                    this.RaisePropertyChanged("SeasonBasicView");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FiXiAPIsamples.MatchService.SportBasicView SportBasicView {
            get {
                return this.SportBasicViewField;
            }
            set {
                if ((object.ReferenceEquals(this.SportBasicViewField, value) != true)) {
                    this.SportBasicViewField = value;
                    this.RaisePropertyChanged("SportBasicView");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((this.StartTimeField.Equals(value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MatchDetailView", Namespace="http://schemas.datacontract.org/2004/07/FiXi.DataContract")]
    [System.SerializableAttribute()]
    public partial class MatchDetailView : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AllocationSeriesIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FiXiAPIsamples.MatchService.TeamDetailFinancialView AwayTeamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FiXiAPIsamples.MatchService.DivisionAttendanceView DivisionAttendanceViewField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FiXiAPIsamples.MatchService.TeamDetailFinancialView HomeTeamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ModifiedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FiXiAPIsamples.MatchService.ResourceListView[] ResourceListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RoundField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FiXiAPIsamples.MatchService.SeasonBasicView SeasonBasicViewField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FiXiAPIsamples.MatchService.SportBasicView SportBasicViewField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AllocationSeriesId {
            get {
                return this.AllocationSeriesIdField;
            }
            set {
                if ((this.AllocationSeriesIdField.Equals(value) != true)) {
                    this.AllocationSeriesIdField = value;
                    this.RaisePropertyChanged("AllocationSeriesId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FiXiAPIsamples.MatchService.TeamDetailFinancialView AwayTeam {
            get {
                return this.AwayTeamField;
            }
            set {
                if ((object.ReferenceEquals(this.AwayTeamField, value) != true)) {
                    this.AwayTeamField = value;
                    this.RaisePropertyChanged("AwayTeam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Created {
            get {
                return this.CreatedField;
            }
            set {
                if ((this.CreatedField.Equals(value) != true)) {
                    this.CreatedField = value;
                    this.RaisePropertyChanged("Created");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FiXiAPIsamples.MatchService.DivisionAttendanceView DivisionAttendanceView {
            get {
                return this.DivisionAttendanceViewField;
            }
            set {
                if ((object.ReferenceEquals(this.DivisionAttendanceViewField, value) != true)) {
                    this.DivisionAttendanceViewField = value;
                    this.RaisePropertyChanged("DivisionAttendanceView");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((this.EndTimeField.Equals(value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FiXiAPIsamples.MatchService.TeamDetailFinancialView HomeTeam {
            get {
                return this.HomeTeamField;
            }
            set {
                if ((object.ReferenceEquals(this.HomeTeamField, value) != true)) {
                    this.HomeTeamField = value;
                    this.RaisePropertyChanged("HomeTeam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Modified {
            get {
                return this.ModifiedField;
            }
            set {
                if ((this.ModifiedField.Equals(value) != true)) {
                    this.ModifiedField = value;
                    this.RaisePropertyChanged("Modified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FiXiAPIsamples.MatchService.ResourceListView[] ResourceList {
            get {
                return this.ResourceListField;
            }
            set {
                if ((object.ReferenceEquals(this.ResourceListField, value) != true)) {
                    this.ResourceListField = value;
                    this.RaisePropertyChanged("ResourceList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Round {
            get {
                return this.RoundField;
            }
            set {
                if ((this.RoundField.Equals(value) != true)) {
                    this.RoundField = value;
                    this.RaisePropertyChanged("Round");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FiXiAPIsamples.MatchService.SeasonBasicView SeasonBasicView {
            get {
                return this.SeasonBasicViewField;
            }
            set {
                if ((object.ReferenceEquals(this.SeasonBasicViewField, value) != true)) {
                    this.SeasonBasicViewField = value;
                    this.RaisePropertyChanged("SeasonBasicView");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FiXiAPIsamples.MatchService.SportBasicView SportBasicView {
            get {
                return this.SportBasicViewField;
            }
            set {
                if ((object.ReferenceEquals(this.SportBasicViewField, value) != true)) {
                    this.SportBasicViewField = value;
                    this.RaisePropertyChanged("SportBasicView");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((this.StartTimeField.Equals(value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TeamDetailFinancialView", Namespace="http://schemas.datacontract.org/2004/07/FiXi.DataContract")]
    [System.SerializableAttribute()]
    public partial class TeamDetailFinancialView : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal BalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal DiscountRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiscountTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ModifiedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FiXiAPIsamples.MatchService.CustomerAsPlayerDetailView[] PlayerViewListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal RegistrationBalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FiXiAPIsamples.MatchService.StatusEnum StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TeamRegistrationFeeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FiXiAPIsamples.MatchService.UpcomingMatchView[] UpcomingMatchListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal WeeklyFeeDueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal WeeklyFeePaidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Balance {
            get {
                return this.BalanceField;
            }
            set {
                if ((this.BalanceField.Equals(value) != true)) {
                    this.BalanceField = value;
                    this.RaisePropertyChanged("Balance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Created {
            get {
                return this.CreatedField;
            }
            set {
                if ((this.CreatedField.Equals(value) != true)) {
                    this.CreatedField = value;
                    this.RaisePropertyChanged("Created");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal DiscountRate {
            get {
                return this.DiscountRateField;
            }
            set {
                if ((this.DiscountRateField.Equals(value) != true)) {
                    this.DiscountRateField = value;
                    this.RaisePropertyChanged("DiscountRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiscountType {
            get {
                return this.DiscountTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.DiscountTypeField, value) != true)) {
                    this.DiscountTypeField = value;
                    this.RaisePropertyChanged("DiscountType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Modified {
            get {
                return this.ModifiedField;
            }
            set {
                if ((this.ModifiedField.Equals(value) != true)) {
                    this.ModifiedField = value;
                    this.RaisePropertyChanged("Modified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FiXiAPIsamples.MatchService.CustomerAsPlayerDetailView[] PlayerViewList {
            get {
                return this.PlayerViewListField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayerViewListField, value) != true)) {
                    this.PlayerViewListField = value;
                    this.RaisePropertyChanged("PlayerViewList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal RegistrationBalance {
            get {
                return this.RegistrationBalanceField;
            }
            set {
                if ((this.RegistrationBalanceField.Equals(value) != true)) {
                    this.RegistrationBalanceField = value;
                    this.RaisePropertyChanged("RegistrationBalance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FiXiAPIsamples.MatchService.StatusEnum Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TeamRegistrationFee {
            get {
                return this.TeamRegistrationFeeField;
            }
            set {
                if ((this.TeamRegistrationFeeField.Equals(value) != true)) {
                    this.TeamRegistrationFeeField = value;
                    this.RaisePropertyChanged("TeamRegistrationFee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FiXiAPIsamples.MatchService.UpcomingMatchView[] UpcomingMatchList {
            get {
                return this.UpcomingMatchListField;
            }
            set {
                if ((object.ReferenceEquals(this.UpcomingMatchListField, value) != true)) {
                    this.UpcomingMatchListField = value;
                    this.RaisePropertyChanged("UpcomingMatchList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal WeeklyFeeDue {
            get {
                return this.WeeklyFeeDueField;
            }
            set {
                if ((this.WeeklyFeeDueField.Equals(value) != true)) {
                    this.WeeklyFeeDueField = value;
                    this.RaisePropertyChanged("WeeklyFeeDue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal WeeklyFeePaid {
            get {
                return this.WeeklyFeePaidField;
            }
            set {
                if ((this.WeeklyFeePaidField.Equals(value) != true)) {
                    this.WeeklyFeePaidField = value;
                    this.RaisePropertyChanged("WeeklyFeePaid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DivisionAttendanceView", Namespace="http://schemas.datacontract.org/2004/07/FiXi.DataContract")]
    [System.SerializableAttribute()]
    public partial class DivisionAttendanceView : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FiXiAPIsamples.MatchService.DivisionBasicView DivisionBasicViewField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MinimumAttendanceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FiXiAPIsamples.MatchService.DivisionBasicView DivisionBasicView {
            get {
                return this.DivisionBasicViewField;
            }
            set {
                if ((object.ReferenceEquals(this.DivisionBasicViewField, value) != true)) {
                    this.DivisionBasicViewField = value;
                    this.RaisePropertyChanged("DivisionBasicView");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MinimumAttendance {
            get {
                return this.MinimumAttendanceField;
            }
            set {
                if ((this.MinimumAttendanceField.Equals(value) != true)) {
                    this.MinimumAttendanceField = value;
                    this.RaisePropertyChanged("MinimumAttendance");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SeasonBasicView", Namespace="http://schemas.datacontract.org/2004/07/FiXi.DataContract")]
    [System.SerializableAttribute()]
    public partial class SeasonBasicView : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SportBasicView", Namespace="http://schemas.datacontract.org/2004/07/FiXi.DataContract")]
    [System.SerializableAttribute()]
    public partial class SportBasicView : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColorHTMLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextColorHTMLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ColorHTML {
            get {
                return this.ColorHTMLField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorHTMLField, value) != true)) {
                    this.ColorHTMLField = value;
                    this.RaisePropertyChanged("ColorHTML");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TextColorHTML {
            get {
                return this.TextColorHTMLField;
            }
            set {
                if ((object.ReferenceEquals(this.TextColorHTMLField, value) != true)) {
                    this.TextColorHTMLField = value;
                    this.RaisePropertyChanged("TextColorHTML");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResourceListView", Namespace="http://schemas.datacontract.org/2004/07/FiXi.DataContract")]
    [System.SerializableAttribute()]
    public partial class ResourceListView : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerAsPlayerDetailView", Namespace="http://schemas.datacontract.org/2004/07/FiXi.DataContract")]
    [System.SerializableAttribute()]
    public partial class CustomerAsPlayerDetailView : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DOBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool MatchAttendedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MatchesAttendedPostRegistrationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MatchesAttendedPreRegistrationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ModifiedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RegistrationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RegistrationExpiryDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FiXiAPIsamples.MatchService.PlayerRoleEnum RoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShirtNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FiXiAPIsamples.MatchService.PlayerStatusEnum StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SuburbField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Created {
            get {
                return this.CreatedField;
            }
            set {
                if ((this.CreatedField.Equals(value) != true)) {
                    this.CreatedField = value;
                    this.RaisePropertyChanged("Created");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DOB {
            get {
                return this.DOBField;
            }
            set {
                if ((this.DOBField.Equals(value) != true)) {
                    this.DOBField = value;
                    this.RaisePropertyChanged("DOB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool MatchAttended {
            get {
                return this.MatchAttendedField;
            }
            set {
                if ((this.MatchAttendedField.Equals(value) != true)) {
                    this.MatchAttendedField = value;
                    this.RaisePropertyChanged("MatchAttended");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MatchesAttendedPostRegistration {
            get {
                return this.MatchesAttendedPostRegistrationField;
            }
            set {
                if ((this.MatchesAttendedPostRegistrationField.Equals(value) != true)) {
                    this.MatchesAttendedPostRegistrationField = value;
                    this.RaisePropertyChanged("MatchesAttendedPostRegistration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MatchesAttendedPreRegistration {
            get {
                return this.MatchesAttendedPreRegistrationField;
            }
            set {
                if ((this.MatchesAttendedPreRegistrationField.Equals(value) != true)) {
                    this.MatchesAttendedPreRegistrationField = value;
                    this.RaisePropertyChanged("MatchesAttendedPreRegistration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mobile {
            get {
                return this.MobileField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileField, value) != true)) {
                    this.MobileField = value;
                    this.RaisePropertyChanged("Mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Modified {
            get {
                return this.ModifiedField;
            }
            set {
                if ((this.ModifiedField.Equals(value) != true)) {
                    this.ModifiedField = value;
                    this.RaisePropertyChanged("Modified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Postcode {
            get {
                return this.PostcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostcodeField, value) != true)) {
                    this.PostcodeField = value;
                    this.RaisePropertyChanged("Postcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RegistrationDate {
            get {
                return this.RegistrationDateField;
            }
            set {
                if ((this.RegistrationDateField.Equals(value) != true)) {
                    this.RegistrationDateField = value;
                    this.RaisePropertyChanged("RegistrationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RegistrationExpiryDate {
            get {
                return this.RegistrationExpiryDateField;
            }
            set {
                if ((this.RegistrationExpiryDateField.Equals(value) != true)) {
                    this.RegistrationExpiryDateField = value;
                    this.RaisePropertyChanged("RegistrationExpiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FiXiAPIsamples.MatchService.PlayerRoleEnum Role {
            get {
                return this.RoleField;
            }
            set {
                if ((this.RoleField.Equals(value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShirtNumber {
            get {
                return this.ShirtNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ShirtNumberField, value) != true)) {
                    this.ShirtNumberField = value;
                    this.RaisePropertyChanged("ShirtNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FiXiAPIsamples.MatchService.PlayerStatusEnum Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Suburb {
            get {
                return this.SuburbField;
            }
            set {
                if ((object.ReferenceEquals(this.SuburbField, value) != true)) {
                    this.SuburbField = value;
                    this.RaisePropertyChanged("Suburb");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusEnum", Namespace="http://schemas.datacontract.org/2004/07/FiXi.DataContract")]
    public enum StatusEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Active = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Inactive = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpcomingMatchView", Namespace="http://schemas.datacontract.org/2004/07/FiXi.DataContract")]
    [System.SerializableAttribute()]
    public partial class UpcomingMatchView : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FiXiAPIsamples.MatchService.TeamBasicView AwayTeamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FiXiAPIsamples.MatchService.DivisionBasicView DivisionBasicViewField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FiXiAPIsamples.MatchService.TeamBasicView HomeTeamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime MatchTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FiXiAPIsamples.MatchService.ResourceListView ResourceListViewField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FiXiAPIsamples.MatchService.SeasonBasicView SeasonBasicViewField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FiXiAPIsamples.MatchService.SportBasicView SportBasicViewField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FiXiAPIsamples.MatchService.TeamBasicView AwayTeam {
            get {
                return this.AwayTeamField;
            }
            set {
                if ((object.ReferenceEquals(this.AwayTeamField, value) != true)) {
                    this.AwayTeamField = value;
                    this.RaisePropertyChanged("AwayTeam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FiXiAPIsamples.MatchService.DivisionBasicView DivisionBasicView {
            get {
                return this.DivisionBasicViewField;
            }
            set {
                if ((object.ReferenceEquals(this.DivisionBasicViewField, value) != true)) {
                    this.DivisionBasicViewField = value;
                    this.RaisePropertyChanged("DivisionBasicView");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FiXiAPIsamples.MatchService.TeamBasicView HomeTeam {
            get {
                return this.HomeTeamField;
            }
            set {
                if ((object.ReferenceEquals(this.HomeTeamField, value) != true)) {
                    this.HomeTeamField = value;
                    this.RaisePropertyChanged("HomeTeam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime MatchTime {
            get {
                return this.MatchTimeField;
            }
            set {
                if ((this.MatchTimeField.Equals(value) != true)) {
                    this.MatchTimeField = value;
                    this.RaisePropertyChanged("MatchTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FiXiAPIsamples.MatchService.ResourceListView ResourceListView {
            get {
                return this.ResourceListViewField;
            }
            set {
                if ((object.ReferenceEquals(this.ResourceListViewField, value) != true)) {
                    this.ResourceListViewField = value;
                    this.RaisePropertyChanged("ResourceListView");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FiXiAPIsamples.MatchService.SeasonBasicView SeasonBasicView {
            get {
                return this.SeasonBasicViewField;
            }
            set {
                if ((object.ReferenceEquals(this.SeasonBasicViewField, value) != true)) {
                    this.SeasonBasicViewField = value;
                    this.RaisePropertyChanged("SeasonBasicView");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FiXiAPIsamples.MatchService.SportBasicView SportBasicView {
            get {
                return this.SportBasicViewField;
            }
            set {
                if ((object.ReferenceEquals(this.SportBasicViewField, value) != true)) {
                    this.SportBasicViewField = value;
                    this.RaisePropertyChanged("SportBasicView");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerRoleEnum", Namespace="http://schemas.datacontract.org/2004/07/FiXi.DataContract")]
    public enum PlayerRoleEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Coach = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PlayerCoach = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Captain = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Player = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Contact = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ViceCaptain = 6,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerStatusEnum", Namespace="http://schemas.datacontract.org/2004/07/FiXi.DataContract")]
    public enum PlayerStatusEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Active = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Inactive = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Suspended = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TeamBasicView", Namespace="http://schemas.datacontract.org/2004/07/FiXi.DataContract")]
    [System.SerializableAttribute()]
    public partial class TeamBasicView : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DivisionBasicView", Namespace="http://schemas.datacontract.org/2004/07/FiXi.DataContract")]
    [System.SerializableAttribute()]
    public partial class DivisionBasicView : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TeamBasicFinancialView", Namespace="http://schemas.datacontract.org/2004/07/FiXi.DataContract")]
    [System.SerializableAttribute()]
    public partial class TeamBasicFinancialView : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal BalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal RoundFeeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FiXiAPIsamples.MatchService.TeamBasicView TeamBasicViewField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Balance {
            get {
                return this.BalanceField;
            }
            set {
                if ((this.BalanceField.Equals(value) != true)) {
                    this.BalanceField = value;
                    this.RaisePropertyChanged("Balance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal RoundFee {
            get {
                return this.RoundFeeField;
            }
            set {
                if ((this.RoundFeeField.Equals(value) != true)) {
                    this.RoundFeeField = value;
                    this.RaisePropertyChanged("RoundFee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FiXiAPIsamples.MatchService.TeamBasicView TeamBasicView {
            get {
                return this.TeamBasicViewField;
            }
            set {
                if ((object.ReferenceEquals(this.TeamBasicViewField, value) != true)) {
                    this.TeamBasicViewField = value;
                    this.RaisePropertyChanged("TeamBasicView");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetMatchByIdRequest", Namespace="http://schemas.datacontract.org/2004/07/FiXi.DataContract")]
    [System.SerializableAttribute()]
    public partial class GetMatchByIdRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ApplicationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ApplicationId {
            get {
                return this.ApplicationIdField;
            }
            set {
                if ((this.ApplicationIdField.Equals(value) != true)) {
                    this.ApplicationIdField = value;
                    this.RaisePropertyChanged("ApplicationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetMatchesByIdListRequest", Namespace="http://schemas.datacontract.org/2004/07/FiXi.DataContract")]
    [System.SerializableAttribute()]
    public partial class GetMatchesByIdListRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ApplicationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] MatchIdListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ApplicationId {
            get {
                return this.ApplicationIdField;
            }
            set {
                if ((this.ApplicationIdField.Equals(value) != true)) {
                    this.ApplicationIdField = value;
                    this.RaisePropertyChanged("ApplicationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] MatchIdList {
            get {
                return this.MatchIdListField;
            }
            set {
                if ((object.ReferenceEquals(this.MatchIdListField, value) != true)) {
                    this.MatchIdListField = value;
                    this.RaisePropertyChanged("MatchIdList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://FiXi.Contracts/PrivateServices", ConfigurationName="MatchService.IMatchService")]
    public interface IMatchService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://FiXi.Contracts/PrivateServices/IMatchService/GetMatchesByDateRange", ReplyAction="http://FiXi.Contracts/PrivateServices/IMatchService/GetMatchesByDateRangeResponse" +
            "")]
        FiXiAPIsamples.MatchService.GetMatchesByDateRangeResponse GetMatchesByDateRange(FiXiAPIsamples.MatchService.GetMatchesByDateRangeRequest GetMatchesByDateRangeRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://FiXi.Contracts/PrivateServices/IMatchService/GetMatchById", ReplyAction="http://FiXi.Contracts/PrivateServices/IMatchService/GetMatchByIdResponse")]
        FiXiAPIsamples.MatchService.GetMatchByIdResponse GetMatchById(FiXiAPIsamples.MatchService.GetMatchByIdRequest GetMatchByIdRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://FiXi.Contracts/PrivateServices/IMatchService/GetMatchesByIdList", ReplyAction="http://FiXi.Contracts/PrivateServices/IMatchService/GetMatchesByIdListResponse")]
        FiXiAPIsamples.MatchService.GetMatchesByIdListResponse GetMatchesByIdList(FiXiAPIsamples.MatchService.GetMatchesByIdListRequest GetMatchesByIdListRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMatchServiceChannel : FiXiAPIsamples.MatchService.IMatchService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MatchServiceClient : System.ServiceModel.ClientBase<FiXiAPIsamples.MatchService.IMatchService>, FiXiAPIsamples.MatchService.IMatchService {
        
        public MatchServiceClient() {
        }
        
        public MatchServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MatchServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MatchServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MatchServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FiXiAPIsamples.MatchService.GetMatchesByDateRangeResponse GetMatchesByDateRange(FiXiAPIsamples.MatchService.GetMatchesByDateRangeRequest GetMatchesByDateRangeRequest) {
            return base.Channel.GetMatchesByDateRange(GetMatchesByDateRangeRequest);
        }
        
        public FiXiAPIsamples.MatchService.GetMatchByIdResponse GetMatchById(FiXiAPIsamples.MatchService.GetMatchByIdRequest GetMatchByIdRequest) {
            return base.Channel.GetMatchById(GetMatchByIdRequest);
        }
        
        public FiXiAPIsamples.MatchService.GetMatchesByIdListResponse GetMatchesByIdList(FiXiAPIsamples.MatchService.GetMatchesByIdListRequest GetMatchesByIdListRequest) {
            return base.Channel.GetMatchesByIdList(GetMatchesByIdListRequest);
        }
    }
}
